[project]
name = "simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anywidget>=0.9.18",
    "matplotlib>=3.10.6",
    "networkx>=3.5",
    "plotly>=6.3.1",
    "streamlit>=1.50.0",
]
